### ISSUE TITLE
ztid hangs during 0-OS boot

### ISSUE THREAD

**Issue by zaibon** [threefoldtech/ztid#1]
We have come up in a situation where ztid hangs forever and prevent a 0-OS node to boot.
After running an strace on ztid, it turns out it is blocked on an `mmap` call.

![strace](https://user-images.githubusercontent.com/303164/53805663-16da1980-3f4b-11e9-9fb3-a72a9949f8fa.png)

**Comment by maxux** [comment]
And what about the `rewrite-c` branch ?

**Comment by zaibon** [comment]
@muhamadazmy which branch do you use in 0-OS nowadays ?
@maxux what is this branch exactly ?

**Comment by maxux** [comment]
@zaibon exactly the same as the Go one, but without Go. What's the point doing it in Go when 99% of the project is C++ with tricky binding to Go :p

**Comment by zaibon** [comment]
Just did the test, both version produce same result. I guess it's worth trying the C version see if it have the same issue.

**Comment by muhamadazmy** [comment]
> @muhamadazmy which branch do you use in 0-OS nowadays ?

We use master. 
Also regarding trying the C version, i assume you mean the tool bundled inside zerotier itself. Chris can try running `zerotier-idtool generate` on the machine directly, but notice that this one generates a random ID. I start thinking that may be the seed we provide (the mash of macs) might be invalid or something, not sure if this is even possible.

**Comment by chrisvdg** [comment]
Is it possible to add logs on the creation of the seed etc?

**Comment by chrisvdg** [comment]
Changed the mac address of eno2 to change the seed

```sh
~ # ip a l
1: lo: <LOOPBACK,UP,LOWER_UP> mtu 65536 qdisc noqueue state UNKNOWN group default qlen 1000
    link/loopback 00:00:00:00:00:00 brd 00:00:00:00:00:00
    inet 127.0.0.1/8 scope host lo
       valid_lft forever preferred_lft forever
    inet6 ::1/128 scope host 
       valid_lft forever preferred_lft forever
2: eno1: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 1500 qdisc mq state UP group default qlen 1000
    link/ether ac:1f:6b:47:a0:1c brd ff:ff:ff:ff:ff:ff
    inet 10.10.210.88/23 scope global eno1
       valid_lft forever preferred_lft forever
    inet6 fe80::ae1f:6bff:fe47:a01c/64 scope link 
       valid_lft forever preferred_lft forever
3: eno2: <NO-CARRIER,BROADCAST,MULTICAST,UP> mtu 1500 qdisc mq state DOWN group default qlen 1000
    link/ether ac:1f:6b:47:a0:1d brd ff:ff:ff:ff:ff:ff

~ # ip link set dev eno2 address ac:1f:6b:47:a1:1d

~ # ./ztid --out /tmp/test --debug
DEBU[0000] calculating machine identity                 
DEBU[0000] nics found                                    count=10
DEBU[0000] reading motherboard id                       
DEBU[0000] adding device to list of identity devices     mac="ac:1f:6b:47:a0:1c" nic=eno1
DEBU[0000] adding device to list of identity devices     mac="ac:1f:6b:47:a1:1d" nic=eno2
DEBU[0000] adding device to list of identity devices     mac="ac:1f:6b:47:a0:1e" nic=eno3
DEBU[0000] adding device to list of identity devices     mac="ac:1f:6b:47:a0:1f" nic=eno4
DEBU[0000] adding device to list of identity devices     mac="ac:1f:6b:8d:2a:60" nic=enp2s0f0
DEBU[0000] adding device to list of identity devices     mac="ac:1f:6b:8d:2a:61" nic=enp2s0f1
DEBU[0000] macs used in identity generation (sorted)     count=6 macs="[ac:1f:6b:47:a0:1c ac:1f:6b:47:a0:1e ac:1f:6b:47:a0:1f ac:1f:6b:47:a1:1d ac:1f:6b:8d:2a:60 ac:1f:6b:8d:2a:61]"
INFO[0000] generating identity ...                      
DEBU[0000] calling the underlaying C generate function  
DEBU[0000] generation complete                          
DEBU[0000] writing identity files    
```

**Comment by muhamadazmy** [comment]
We use the mac to generate a seed, that we feed to the id generator where a strong random is expected, hence we grantee the same generated id everytime. So, this unlucky machine has a set of mac addresses that generates a faulty seed some how!!

**Comment by zaibon** [comment]
@muhamadazmy is there any documentation about the nature of the seed? what are the requirements for a valid seed somewhere ?

**Comment by zaibon** [comment]
we don't need ztid anymore in 0-OS v2
